"""Detailed, player-facing rules for the role guide page."""


ROLE_CAMPS = {
    "simple_wolves": "wolf", "infecting_fathers": "wolf", "cerberus_wolves": "wolf",
    "black_wolves": "wolf", "talkative_wolves": "wolf", "blue_wolves": "wolf",
    "white_wolves": "solo", "aliens": "solo", "pyromaniacs": "solo", "angels": "solo",
    "barbers": "village", "prostitutes": "village", "servants": "village",
    "ancients": "village", "hunters": "village", "red_riding_hoods": "village", "bears": "village",
    "shepherds": "village", "cupids": "village", "judges": "village",
    "wild_children": "variable", "ankous": "village", "little_girls": "village",
    "seers": "village", "witches": "village", "protectors": "village",
    "villagers": "village",
}


ROLE_CODES = {
    "simple_wolves": "LG", "infecting_fathers": "LPI", "cerberus_wolves": "LC",
    "black_wolves": "LN", "talkative_wolves": "LB", "blue_wolves": "BL",
    "white_wolves": "LW", "barbers": "BA", "aliens": "AL", "pyromaniacs": "PY", "prostitutes": "PU",
    "servants": "SE", "ancients": "AN", "hunters": "CH", "red_riding_hoods": "CR", "bears": "OU",
    "shepherds": "BE", "cupids": "CU", "judges": "JU", "wild_children": "ES",
    "angels": "AG", "ankous": "AK", "little_girls": "PF", "seers": "VO",
    "witches": "SO", "protectors": "PR", "villagers": "VI",
}


ROLE_GUIDES = {
    "fr": {
        "simple_wolves": (
            "Se réveille avec la meute chaque nuit. La meute choisit une seule cible non-loup.",
            "Si les loups voient quelqu'un regarder, ils peuvent remplacer leur première cible par cette personne. Le narrateur ne confirme jamais son rôle.",
            "Le blocage du Loup Cerbère n'enlève aucune capacité spéciale au Loup simple. Infecté ou amoureux, son clan est recalculé selon les règles de l'infection et du Couple.",
        ),
        "infecting_fathers": (
            "Chasse avec la meute et possède une seule cartouche d'infection pour toute la partie. Il décide après le choix final des loups.",
            "Toute tentative consomme la cartouche. Si la meute cible la Pute non bloquée, la personne chez qui elle dort devient la cible de l'infection. Protection, Ancien, Alien et Servante non bloquée peuvent faire échouer une tentative.",
            "Le Cerbère bloque son tour d'infection sans consommer la cartouche. La cible conserve son rôle original et tous ses pouvoirs ; son Couple peut ensuite remplacer le clan loup selon les règles des amoureux.",
        ),
        "cerberus_wolves": (
            "Se réveille avant la meute et choisit un autre joueur dont le pouvoir est bloqué pour la nuit en cours. Il ne peut pas bloquer le même joueur deux nuits consécutives.",
            "Le narrateur réveille normalement les rôles nocturnes ciblés sans révéler le blocage. Ours, Berger et Juge reçoivent un résultat inversé, la Voyante voit le Loup Cerbère et le Pyromane reste visible mais désactivé. Les pouvoirs de jour ne sont jamais bloqués.",
            "Protection, absence de la Pute, potions, infection, tir du Loup Blanc, silence, mot imposé, actions du Pyromane et protection passive du Chaperon Rouge sont annulés sans consommer les ressources.",
        ),
        "black_wolves": (
            "Se réveille seul chaque nuit et désigne le joueur réduit au silence le lendemain.",
            "Le joueur doit dire « Passe » pendant la parole et les accusations, et son vote ne compte pas.",
            "S'il est bloqué par le Cerbère, aucun silence n'est imposé. Il chasse toujours normalement avec la meute et suit les règles de clan du Couple.",
        ),
        "talkative_wolves": (
            "Se réveille seul, choisit un joueur et lui impose un mot à prononcer pendant sa prise de parole du lendemain. Il ne peut pas choisir le même joueur deux nuits consécutives.",
            "Le narrateur affiche le joueur et le mot pendant la journée. Le rôle ne tue personne directement.",
            "Le Cerbère annule le mot de cette nuit. Il reste membre physique de la meute pour l'Ours, le Berger, le Juge et les Couples.",
        ),
        "blue_wolves": (
            "Chasse normalement avec la meute, mais trompe la Voyante.",
            "Quand la Voyante le vise, l'interface affiche un rôle aléatoire parmi les rôles des joueurs encore en vie, y compris Loup Bleu.",
            "Bloquer le Loup Bleu ne retire pas son camouflage. Si la Voyante elle-même est bloquée, elle voit le Cerbère. Il appartient au clan loup sauf changement par Couple Alien ou mixte.",
        ),
        "white_wolves": (
            "Chasse avec la meute toutes les nuits. Les sous-rôles des loups restent cachés pendant leur discussion.",
            "Les nuits 2, 4, 6… il se réveille seul et peut tuer directement un autre membre physique de la meute, ou passer. Le Cerbère annule ce tir pour la nuit.",
            "Solitaire, il bloque la victoire de la meute par parité et gagne seulement comme unique survivant. Amoureux d'un loup, il forme un Couple indépendant et ne peut jamais tuer son partenaire.",
        ),
        "barbers": (
            "La première nuit, convient d'un clin d'œil avec le narrateur. Il peut utiliser son unique cartouche au réveil, pendant les discussions ou pendant le vote final.",
            "Seul un rôle Loup distribué au début de la partie est une bonne cible et meurt seul. Un joueur infecté ou un Enfant Sauvage transformé compte comme une erreur : le Barbier et la cible meurent ensemble.",
            "Le Cerbère ne peut pas bloquer ce pouvoir de jour : le signal et le tir restent disponibles. Infecté ou en Couple, il conserve son rôle et son tir.",
        ),
        "aliens": (
            "Joue en solo et peut utiliser son signal sans limite pendant les discussions ou le vote final. À chaque tentative, il peut viser autant de survivants non validés qu'il le souhaite et attribuer un rôle à chacun.",
            "Les réponses sont vérifiées dans l'ordre choisi. Chaque bonne réponse tue son joueur ; à la première erreur, l'Alien meurt et toutes les réponses suivantes sont ignorées, donc leurs cibles restent en vie.",
            "Une mort ne donne jamais une victoire automatique. Si tous les survivants sont déjà validés après des morts, il doit effectuer un contact final au signal suivant. Son immunité à l'attaque et à l'infection est une règle maison explicite ; la Sorcière peut le tuer.",
            "Le Cerbère ne peut pas bloquer ce pouvoir de jour : le signal et la tentative restent disponibles. Ses immunités passives restent actives. Un Couple contenant un Alien rejoint normalement le clan Alien.",
        ),
        "pyromaniacs": (
            "Se réveille chaque nuit et choisit exactement une action : asperger d’huile un ou deux autres joueurs, ou incendier tous les joueurs déjà aspergés.",
            "Il ne peut jamais asperger et incendier la même nuit. Un incendie tue directement toutes les cibles aspergées, ignore les protections, puis vide entièrement la liste d’huile ; il peut recommencer à asperger dès la nuit suivante.",
            "Le Cerbère bloque les deux actions pour une nuit sans retirer l’huile déjà posée. Les boutons restent visibles, désactivés et rouges. Le Pyromane joue seul et gagne lorsqu’il est le dernier survivant.",
        ),
        "prostitutes": (
            "Chaque nuit, choisit un autre joueur chez qui dormir. Si la meute cible la Pute, son attaque est redirigée vers la personne visitée, qui peut mourir ou être infectée.",
            "Si les loups ciblent directement la personne visitée, elle subit aussi l'attaque normalement. La protection et les immunités sont vérifiées sur la cible finale.",
            "Si le Cerbère la bloque, la redirection et son immunité à l'infection disparaissent : la Pute reste la cible et peut être tuée ou infectée. Sa visite reste enregistrée pour la règle de répétition.",
        ),
        "servants": (
            "Après une élimination par vote et avant l'annonce publique, peut prendre secrètement le rôle du joueur éliminé ou rester Servante.",
            "Elle reprend la carte dans son état actuel : potions, cartouches, découvertes, dernières cibles, vies déjà perdues, modèle et objectif échoué. Elle ne reprend pas l'infection ni les autres états personnels de l'ancien propriétaire.",
            "Si le joueur éliminé appartient au Couple, accepter son rôle remplace aussi ce joueur par la Servante dans le Couple : son partenaire reste vivant. Si elle refuse, le partenaire meurt normalement en chaîne.",
            "Normalement, la Servante est immunisée à l'infection : la tentative échoue, l'attaque est annulée et la cartouche du Loup-Père est quand même consommée.",
            "Si le Cerbère la bloque, son immunité nocturne disparaît : l'infection réussit et utilise normalement la cartouche. Elle rejoint les loups, conserve son rôle et garde son choix d'héritage de jour, qui ne peut pas être bloqué.",
            "Si elle hérite ensuite d'une autre carte, son statut infecté reste personnel et la suit. La victoire terminale de l'Ange reste prioritaire et empêche tout héritage.",
        ),
        "ancients": (
            "Possède deux vies uniquement contre l'attaque normale de la meute. La première attaque enlève une vie, la seconde le tue.",
            "Potion de mort, tir du Chasseur, Barbier et autres morts directes le tuent immédiatement. Seule son élimination par le vote désactive définitivement tous les pouvoirs du Village, tir du Chasseur inclus ; chacun garde néanmoins son rôle. Toute autre cause de mort ne retire aucun pouvoir.",
            "Il est totalement immunisé à l'infection : elle ne le transforme pas et ne lui retire aucune vie. La Servante qui hérite de sa carte reprend le nombre de vies restant. Le Cerbère ne retire pas ses vies.",
        ),
        "hunters": (
            "Quand il meurt de nuit, par vote ou par le tir d'un autre Chasseur, il choisit un joueur vivant à emporter avec lui.",
            "Les tirs peuvent former une chaîne de Chasseurs. Après la pénalité de mort de l'Ancien, il conserve son rôle de Chasseur mais perd définitivement son tir.",
            "Le Cerbère n'annule pas son dernier tir. Infecté ou en Couple, il tire encore à sa mort, sauf si la pénalité de l'Ancien a déjà désactivé son pouvoir.",
        ),
        "red_riding_hoods": (
            "Son pouvoir est entièrement passif : tant qu'au moins un Chasseur est vivant, l'attaque normale de la meute ne peut pas la tuer.",
            "Si tous les Chasseurs sont morts, elle redevient une cible normale. Potion de mort, Loup Blanc, Chasseur, Barbier, vote et autres morts directes ignorent cette protection.",
            "Si le Cerbère bloque le Chaperon Rouge, sa protection est suspendue pour cette nuit même si un Chasseur vit encore. L'interface affiche alors le statut rouge « Protection bloquée par le Loup Cerbère » ; la protection revient automatiquement ensuite.",
        ),
        "bears": (
            "Après une inscription par QR code, le narrateur classe les joueurs dans leur ordre réel autour de la table. La liste est circulaire : le dernier joueur est voisin du premier.",
            "Chaque nuit, le jeu vérifie ses deux voisins vivants les plus proches autour de la table. Il grogne si au moins un est loup ou infecté.",
            "Après une mort, les voisins sont recalculés. Avant la première nuit, le narrateur décide si un Ours infecté grogne automatiquement et si le résultat est calculé à la tombée de la nuit ou après les pouvoirs nocturnes.",
            "Le Cerbère inverse le résultat : l'Ours reste silencieux avec un voisin loup et grogne si aucun voisin n'est loup. L'infection le fait rejoindre la meute sans perdre son pouvoir.",
        ),
        "shepherds": (
            "Après la distribution, le narrateur choisit son stock initial de un à dix moutons. Chaque nuit, il peut n'en envoyer aucun ou en envoyer autant qu'il lui en reste, vers des joueurs vivants différents.",
            "Un mouton revient si la cible n'est pas membre physique de la meute ; il est perdu définitivement si la cible est loup. À zéro mouton, le Berger ne se réveille plus.",
            "Le Cerbère inverse chaque résultat : le mouton revient d'un loup et se perd chez un non-loup. Infecté, il rejoint les loups mais reste Berger et continue ses envois.",
        ),
        "cupids": (
            "La première nuit, choisit deux joueurs différents et peut se choisir lui-même avec une autre personne.",
            "Deux membres du même camp continuent avec ce camp. Infecté + loup normal restent avec la meute ; infecté + villageois ou rôle solo forment un Couple indépendant. Sans infecté, tout Couple contenant un Alien rejoint le clan Alien.",
            "Le Cerbère agit après Cupidon et ne peut donc pas annuler le lien déjà créé. Les pouvoirs individuels restent actifs et le clan du Couple est recalculé après infection ou transformation.",
        ),
        "judges": (
            "Chaque nuit, compare deux joueurs différents et peut se choisir avec une autre personne. Il apprend seulement « même clan » ou « clans différents ».",
            "Le résultat utilise les clans actuels : Village, Loups, Alien ou Couple indépendant. Infection, Enfant Sauvage transformé, Ange expiré et Couples sont donc pris en compte.",
            "Le Cerbère inverse le verdict : deux joueurs du même clan apparaissent de clans différents, et deux joueurs de clans différents apparaissent du même clan. Infecté, il reste Juge et continue ses comparaisons.",
        ),
        "wild_children": (
            "La première nuit, choisit un autre joueur comme modèle.",
            "Dès que ce modèle meurt, quelle qu'en soit la cause (nuit, vote, Barbier, Alien, Chasseur ou mort en chaîne), l'Enfant Sauvage rejoint physiquement la meute tout en gardant son identité.",
            "Transformé ou infecté, il est détecté comme loup par Ours, Berger et Juge, mais conserve le rôle Enfant Sauvage et son lien d'idole. Le Cerbère n'annule pas le choix déjà fait.",
        ),
        "angels": (
            "La partie commence toujours par la nuit 1. L'Ange joue ensuite seul pendant le premier jour et gagne s'il est l'unique éliminé par le premier vote final.",
            "Dès la résolution du premier vote, un échec le transforme en Simple Villageois. S'il devient seul survivant avant ce vote, son objectif échoue et les conditions normales sont appliquées.",
            "Amoureux, il abandonne immédiatement son objectif solo : avec un Villageois, le Couple reste au Village. Le Cerbère n'affecte pas cette règle et la victoire de l'Ange est prioritaire sur la Servante.",
        ),
        "ankous": (
            "Après sa mort, ne parle plus mais conserve un vote secret par jour pendant exactement deux jours de vote. L'application ajoute automatiquement cette voix au total.",
            "Mort de nuit : il vote le jour même puis le suivant. Mort par vote : ses deux votes commencent les deux jours suivants. Un jour où le vote est passé consomme quand même une journée.",
            "Le Cerbère n'annule pas ces votes posthumes. Infecté, il rejoint la meute mais reste Ankou et garde ses deux votes après sa mort, sauf si la pénalité de l'Ancien désactive ce pouvoir.",
        ),
        "little_girls": (
            "Peut entrouvrir les yeux physiquement pendant le tour des loups pour tenter de les reconnaître, sans écran ni confirmation du narrateur.",
            "Les loups choisissent d'abord une victime. S'ils voient quelqu'un regarder, ils peuvent choisir cette personne comme nouvelle cible, qu'elle soit réellement Petite Fille ou non. Une seule cible finale est attaquée.",
            "Le Cerbère agit après ce moment et ne confirme ni n'annule l'observation. Infectée, elle rejoint les loups mais conserve le rôle Petite Fille. Protection, Pute, Sorcière et infection utilisent la cible finale.",
        ),
        "seers": (
            "Chaque nuit, choisit un autre joueur et découvre le rôle affiché par l'interface.",
            "Le Loup Bleu renvoie un rôle entièrement aléatoire. Si la Voyante est bloquée par le Cerbère, elle ne voit que le Loup Cerbère, quelle que soit sa cible.",
            "Une infection la fait rejoindre les loups sans changer son rôle ni ses visions. La Voyante qui observe un infecté voit seulement son rôle original, jamais le statut infecté. En Couple elle garde aussi son pouvoir.",
        ),
        "witches": (
            "Après les loups, voit leur cible finale et possède une potion de vie et une potion de mort, utilisables une seule fois chacune.",
            "Elle peut utiliser les deux potions la même nuit. La vie annule la mort de la cible ; la mort ne peut pas viser la Sorcière elle-même et tue directement Alien, Pute ou Ancien.",
            "Bloquée par le Cerbère, elle se réveille et choisit normalement sans être informée : les effets sont annulés au calcul et aucune potion n'est consommée. Infectée, elle reste Sorcière avec ses potions restantes.",
        ),
        "protectors": (
            "Chaque nuit, choisit un joueur à protéger contre l'attaque de la meute. Il peut se choisir, mais jamais protéger la même personne deux nuits consécutives.",
            "La protection bloque aussi une tentative d'infection sur cette cible, mais la cartouche du Loup-Père est quand même consommée. Elle ne bloque pas potion de mort, Loup Blanc, Chasseur ou Barbier.",
            "Si le Cerbère bloque le Protecteur, son choix n'a aucun effet cette nuit et infection/attaque peuvent passer. Infecté, il rejoint les loups mais reste Protecteur et continue à protéger.",
        ),
        "villagers": (
            "N'a aucun pouvoir nocturne : il observe, discute, accuse et vote avec le Village.",
            "Le Cerbère ne lui retire rien. Le Loup Noir peut annuler sa parole et son vote pour un jour, et le Loup Bavard peut lui imposer un mot.",
            "Une infection le fait rejoindre les loups tout en gardant son rôle de Villageois. En Couple, il garde toujours son rôle original : infecté + loup restent avec la meute, tandis qu'infecté + villageois ou rôle solo deviennent un Couple indépendant.",
        ),
    },
    "en": {
        "simple_wolves": ("Wakes with the pack every night; the pack attacks one non-wolf target.", "If the Wolves see someone peeking, they may replace their first target with that person. The narrator never confirms the person's role.", "A Cerberus block removes no special power from a regular Wolf. Infection and Couple rules can still recalculate its faction."),
        "infecting_fathers": ("Hunts with the pack and owns one infection shot for the entire game, used after the pack's final choice.", "If the pack targets an unblocked Escort, the player hosting her becomes the infection target. Protection, Elder, Alien and an unblocked Servant may still make an attempt fail.", "Every attempt spends the shot, except a Cerberus-blocked turn. The target keeps the original role and powers; Couple rules may override the Wolf faction."),
        "cerberus_wolves": ("Wakes before the pack and blocks one other player's power for the current night. It cannot block the same player on two consecutive nights.", "Night roles still wake normally without learning about the block. Bear, Shepherd and Judge get reversed results, Seer sees Cerberus, and Arsonist remains visible but disabled. Day powers are never blocked.", "Protection, the Escort's absence, potions, infection, White Wolf shot, silence, required words, Arsonist actions and Little Red Riding Hood's passive protection are cancelled without spending resources."),
        "black_wolves": ("Wakes alone and silences one player for the following day.", "That player must answer “Pass” during discussion and accusations, and their vote is not counted.", "Cerberus cancels the silence for that night. The Black Wolf still hunts with the pack and follows Couple faction rules."),
        "talkative_wolves": ("Wakes alone, chooses a player and gives them a word they must say during the next day's speech. It cannot choose the same player on two consecutive nights.", "The narrator displays the player and required word during the day; this power does not kill directly.", "Cerberus cancels the word. The Talkative Wolf remains a physical pack member for Bear, Shepherd, Judge and Couples."),
        "blue_wolves": ("Hunts normally but deceives the Seer.", "When inspected, the interface displays a random role among those of the players still alive, including Blue Wolf.", "Blocking Blue Wolf does not remove the disguise; blocking the Seer shows Cerberus. Couple or Alien links may change its winning faction."),
        "white_wolves": ("Hunts with the pack every night while exact wolf sub-roles stay hidden from the pack.", "On nights 2, 4, 6… it may kill another pack member, never its lover. Cerberus cancels this shot.", "While solo it blocks an early pack parity win and must be the only survivor. With a normal Wolf lover, the Couple becomes independent and must survive together."),
        "barbers": ("Agrees on a wink with the narrator on night one, then has one daytime shot during awakening, discussion or the final vote.", "Only a Wolf role dealt at the start is a correct target and dies alone. An infected player or a transformed Wild Child is a miss: both the Barber and the target die.", "Cerberus cannot block this day power: the signal and shot remain available. Infection or a Couple changes the faction, but Barber keeps the role."),
        "aliens": ("Plays solo and may signal without limit during discussion or the final vote. Each attempt may target as many living unconfirmed players as desired and assign each a role.", "Answers are checked in the chosen order. Each correct answer kills its player; the first mistake kills Alien and every later answer is ignored, so those targets remain alive.", "Deaths never grant an automatic win: when every survivor is known, Alien must make final contact on a later signal.", "Cerberus cannot block this day power: the signal and attempt remain available. Alien's passive immunities remain active, while Witch can still kill Alien."),
        "pyromaniacs": ("Wakes every night and chooses exactly one action: douse one or two other players, or ignite everyone already doused.", "Dousing and ignition can never happen on the same night. Fire directly kills all doused targets, ignores protection, then clears the entire oil list so dousing can restart next night.", "Cerberus blocks both actions for one night without removing existing oil. Both buttons remain visible, disabled and red. Arsonist plays solo and wins as the last survivor."),
        "prostitutes": ("Chooses another player's home to stay at each night. If the pack targets the Escort, the attack is redirected to the player hosting her, who may be killed or infected.", "If the pack directly targets the visited player, that player is attacked normally. Protection and immunities are checked on the final target.", "Cerberus cancels the redirection and infection immunity for that night: the Escort remains the target and may be killed or infected. Her visit still counts for the no-repeat rule."),
        "servants": ("Before a voted player's role is announced, may secretly take that role or remain the Servant, unless Angel already won.", "When the eliminated player is a lover, accepting also replaces that player with the Servant in the Couple, so the partner survives. Refusing causes the normal chained lover death.", "Normally immune to infection: an attempt fails, cancels the attack and still consumes the Alpha Wolf's shot.", "If Cerberus blocks Servant, the night immunity is removed: infection succeeds and uses the shot normally. Servant joins the pack, keeps the role and retains the day inheritance power, which cannot be blocked.", "After inheriting another card, the personal infected status remains."),
        "ancients": ("Has two lives only against normal pack attacks: the first removes one life and the second kills.", "Witch, Hunter and Barber kill immediately. Only elimination by vote permanently disables every Village power, including the Hunter's shot; each player still keeps the same role. Every other cause of death removes no powers.", "Elder is fully immune to infection, which removes no life. A Servant inheriting Elder receives the remaining life count. Cerberus never removes these lives."),
        "hunters": ("After dying at night, by vote or from another Hunter, chooses one living player to take along.", "Hunter shots can chain. After the Elder death penalty, Hunter keeps the role but permanently loses the shot.", "Cerberus does not cancel the last shot. An infected or coupled Hunter still shoots on death unless the Elder penalty has already disabled that power."),
        "red_riding_hoods": ("This power is fully passive: while at least one Hunter is alive, a normal pack attack cannot kill Little Red Riding Hood.", "When every Hunter is dead, the protection ends. Witch poison, White Wolf, Hunter, Barber, vote and other direct deaths ignore it.", "If Cerberus blocks Little Red Riding Hood, the protection is disabled for that night even while a Hunter lives. A red blocked-protection status is shown, and the protection returns automatically afterward."),
        "bears": ("After QR-code registration, the narrator arranges players in their real seating order. The list is circular: the last player neighbours the first.", "Each night, the game checks the two closest living neighbours around the table; the Bear growls when at least one is a Wolf or infected.", "Neighbours are recalculated after deaths. Before night one, the narrator decides whether an infected Bear growls automatically and whether the result is calculated at nightfall or after night powers.", "Cerberus reverses the result: the Bear stays silent beside a Wolf and growls when neither neighbour is a Wolf."),
        "shepherds": ("After distribution, the narrator chooses a starting stock of one to ten sheep. Each night the Shepherd may send none or as many remaining sheep as desired, always to different living players.", "A sheep returns from a non-pack target and is permanently lost against a physical Wolf or infected player. At zero sheep the Shepherd no longer wakes.", "Cerberus reverses each result: sheep return from Wolves and are lost on non-Wolves. An infected Shepherd keeps the role and sheep."),
        "cupids": ("On night one, links two different players and may include Cupid in the pair.", "Same-faction lovers stay together. Infected + normal Wolf remain with the pack; infected + Villager or solo role form an independent Couple. Without infection, any pair containing Alien joins Alien.", "Cerberus acts later and cannot cancel the link. Individual powers remain and the Couple faction is recalculated after infection or transformation."),
        "judges": ("Compares two different players nightly and may choose self plus another player; only learns same or different faction.", "Uses current Village, Wolf, Alien or independent Couple factions: a Village player and an infected player are in different factions.", "Cerberus reverses the verdict: matching factions appear different and different factions appear identical. An infected or coupled Judge keeps the role."),
        "wild_children": ("Chooses another player as a role model on the first night.", "Joins the physical pack whenever the model dies, regardless of the cause: night, vote, Barber, Alien, Hunter or a chained death.", "After changing or infection, Bear, Shepherd and Judge detect a Wolf, but the original Wild Child role and saved model remain. Cerberus does not cancel the model."),
        "angels": ("The game always starts on night one. Angel then plays solo until the first vote and wins alone if uniquely eliminated by it.", "On failure immediately becomes a regular Villager. As the sole survivor before that vote, the objective fails and normal victory is checked.", "A lover Angel immediately abandons the solo goal; with a Villager the Couple stays Village. Angel victory has priority over Servant inheritance."),
        "ankous": ("After death, cannot speak but keeps one secret vote per day for exactly two voting days; the app adds it automatically.", "A night death allows votes that day and the next; a vote death starts on the following two days. A skipped vote still consumes a day.", "Cerberus does not cancel ghost votes. An infected Ankou joins the pack but remains Ankou and keeps both post-death votes, unless the Elder penalty disables this power."),
        "little_girls": ("May physically peek during the Wolves' turn to identify them, without screen help or narrator confirmation.", "Wolves first choose a victim, then may replace it with anyone they saw peeking, whether that person is really Little Girl or not. Only the final target is attacked.", "Cerberus acts later and neither confirms nor cancels peeking. An infected Little Girl joins the pack but keeps the original role; protection, Escort, Witch and infection use the final target."),
        "seers": ("Inspects another player every night and sees the role displayed by the interface.", "Blue Wolf produces a completely random role. For an infected target, the Seer sees only the original role and never the infection. A blocked Seer sees Cerberus.", "An infected or coupled Seer keeps the original role and all future visions; only the winning faction is recalculated."),
        "witches": ("Acts after the Wolves, sees their final target, and may use both one-shot potions in the same night.", "Life cancels the target's death. Death cannot target Witch herself and directly kills Alien, Escort or Elder; killing Elder removes Village powers.", "When blocked, Witch still wakes and chooses without being told; both effects are cancelled at resolution and no potion is spent. Infection or Couple keeps the role and remaining potions."),
        "protectors": ("Protects one player from the pack each night and may protect self, but never the same target on two consecutive nights.", "Also stops infection on that target, although the Alpha's shot is still consumed. It does not stop Witch, White Wolf, Hunter or Barber deaths.", "Cerberus makes that night's protection ineffective. An infected Protector joins the pack but keeps the role and continues protecting."),
        "villagers": ("Has no night power; watches, discusses, accuses and votes with Village.", "Cerberus removes nothing. Black Wolf can remove speech and vote for a day, while Talkative Wolf can impose a word.", "Infection changes the faction to Wolf but preserves the original Villager role. In a Couple, infected + normal Wolf stay with the pack, while infected + Villager or solo role form an independent Couple."),
    },
    "tn": {
        "simple_wolves": ("Yfi9 m3a jme3et el loups kol lil w ya5tarou cible wa7da moch loup.", "Ken chefou joueur yetfarrej, ynajmou ybadlou cible loula bih. El narrateur ma yconfirmi 7atta role.", "Blocage Cerbere ma yna77ilou 7atta pouvoir special. Infection w Couple ynajmou ybadlou clan mte3ou."),
        "infecting_fathers": ("Ysayyed m3a jme3et el loups w 3andou kartoucha infection wa7da fel game, ba3d choix final mta3 loups.", "Ken jme3et el loups ya5tarou Pute moch bloquee, joueur eli r9adet 3andou ywali cible infection. Protection, Ancien, Alien w Servante moch bloquee ynajmou yfachelou tentative.", "Tentative tconsumi kartoucha, sauf ken Cerbere blocka tour. Cible teb9a b role w pouvoirs mte3ha."),
        "cerberus_wolves": ("Yfi9 9bal jme3et el loups w yblocki pouvoir mta3 joueur e5er lel lila hedhi. Ma ynajemch yblocki nafs joueur zouz lilet metwelyin.", "Roles mta3 lil yfi9ou normal bla ma ya3rfou. Ours, Berger w Juge ye5dhou resultat ma9loub, Voyante tchouf Cerbere, w Pyromane yab9a visible ama disabled. Pouvoirs mta3 nhar ma yetblockewch.", "Protection, absence mta3 Pute, potions, infection, tir Loup Blanc, silence, kelma, actions Pyromane w protection passive Chaperon Rouge yetna77aw bla consommation ressources."),
        "black_wolves": ("Yfi9 wa7dou w ysakket joueur lel nhar elli ba3dou.", "Joueur y9oul ken Passe fel parole w accusations, w vote mte3ou ma yet7sebch.", "Cerbere yfas5 silence mta3 ellila. Loup Noir ykammel ysayyed m3a jme3et el loups w yetba3 regles Couple."),
        "talkative_wolves": ("Yfi9 wa7dou, ya5tar joueur w ya3tih kelma lezem y9oulha 8odwa fi klemou. Ma ynajemch ya5tar nafs joueur zouz lilet metwelyin.", "El narrateur ywarrri joueur w kelma fel nhar; pouvoir hedha ma yo9telch direct.", "Cerbere yfas5 kelma. Houwa membre physique men jme3et el loups lel Ours, Berger, Juge w Couples."),
        "blue_wolves": ("Ysayyed normal m3a jme3et el loups ama y8alet el Voyante.", "Ki Voyante ta5tarou, interface twarri role random men roles mta3 joueurs eli mazelou 3aychin, inclus Loup Bleu.", "Blocage mta3 Loup Bleu ma yna77ich camouflage; ken Voyante bloquee tchouf Cerbere. Couple wala Alien ynajem ybaddel clan victoire."),
        "white_wolves": ("Ysayyed m3a jme3et el loups kol lil w sous-roles mta3 loups yab9aw m5obyin.", "Fel lil 2, 4, 6… ynajem yo9tel loup e5er, ama jamais amoureux mte3ou. Cerbere yblocki tir.", "Solo, ywa9ef victoire par parité w lezem yab9a wa7dou. M3a loup amoureux, ywaliw Couple independent w yerb7ou zouz."),
        "barbers": ("Awel lil yetfehem 3la 8amza m3a narrateur. Yesta3mel kartoucha fel fi9a, discussion wala vote final.", "Ken cible role Loup men distribution loula, cible tmout wa7adha. Infecte wala Enfant Sauvage transforme yet7seb guess 8alet: Barbier w cible ymoutou zouz.", "Cerbere ma ynajemch yblocki pouvoir mta3 nhar: signal w kartoucha yab9aw disponibles. Infection wala Couple tbaddel clan bark."),
        "aliens": ("Yal3ab solo w ynajem yesta3mel signal 9addeh ma y7eb waqt discussion wala vote final. Fi kol tentative ynajem ya5tar 9addeh ma y7eb men survivants eli mezelou ma tvalidawch w ya3ti role l kol we7ed.", "Les réponses yetthabtou bel ordre. Kol s7i7a tmout joueur mte3ha; awel 8alta tmout Alien w les réponses eli ba3dha ma yetthabtouch, donc cibles mte3hom yab9aw 7ayyin.", "El mawt ma ya3tihch victoire automatique: ki survivants lkol ma3roufin, lezem contact final b signal.", "Cerbere ma ynajemch yblocki pouvoir mta3 nhar: signal w tentative yab9aw disponibles. Immunités passives yab9aw, w Sorciere tnajem to9tlou."),
        "pyromaniacs": ("Yfi9 kol lil w ya5tar action wa7da: yroch zit 3la joueur wala zouz, wala ycha3el el joueurs eli déjà مرشوشين.", "Ma ynajemch yroch w ycha3el fi nafs el lil. El 7ari9 yo9tel direct el cibles المرشوشين, yet3adda 3al protections, ba3d lista zit تتصفّر w ynajem y3awed yabda ellila jeya.", "Cerbere yblocki zouz actions lila wa7da bla ma yna77i zit eli mawjoud. Les boutons yab9aw visible, disabled w a7mer. Pyromane solo w yerba7 ki yab9a wa7dou."),
        "prostitutes": ("Kol lil ta5tar 3and chkoun ter9od. Ken jme3et el loups ya5tarouha, attaque temchi lel joueur eli r9adet 3andou, w ynajem ymout wala yetinfecta.", "Ken jme3et el loups ya5tarou direct joueur eli r9adet 3andou, houwa zeda yetdhareb normal. Protection w immunites yet7asbou 3la cible finale.", "Ken Cerbere blockeha, redirection w immunite infection yetna77aw: Pute tab9a cible w tnajem tmout wala tetinfecta. El visite tab9a comptabilisee lel no-repeat."),
        "servants": ("9bal annonce mta3 joueur eli 5raj bel vote, tnajem te5ou role mte3ou, sauf ken Ange rba7 deja.", "Ken joueur eli 5raj mel Couple w Servante te5ou role mte3ou, te5ou zeda blasetou fel Couple w partenaire yab9a 3ayech. Ken terfedh, partenaire ymout m3ah normal.", "Normalement ma tetinfectech: tentative tefchel, attaque tetfasa5 w kartoucha mta3 Loup-Pere tetconsuma.", "Ken Cerbere blockeha, immunité mta3 lil tetna77a: infection تنجح w kartoucha temchi s7i7a. Tod5ol m3a les loups, tab9a Servante w pouvoir héritage mta3 nhar ma yetblockech.", "Ken te5ou role e5er, statut infectée yab9a m3aha."),
        "ancients": ("3andou zouz vies ken contre attaque normale mta3 jme3et el loups: loula tna77i vie w thenya to9tlou.", "Sorciere, Chasseur w Barbier yo9tlouh direct. Ken ymout bel vote bark, pouvoirs lkol mta3 Village yetna77aw définitivement, inclus tir Chasseur; ama kol joueur yab9a b nafs role mte3ou. Ay sabab mawt e5er ma yna77i 7atta pouvoir.", "Ancien immunisé 100% mel infection: la yet7awwel la tetna77alou vie. Servante te5ou 3dad vies eli ba9i."),
        "hunters": ("Ki ymout fel lil, bel vote wala b tir Chasseur e5er, ya5tar joueur 3ayech yhezou m3ah.", "Tirs ynajmou ya3mlou chaine. Ba3d pénalité mawt Ancien, Chasseur yab9a b role mte3ou ama tir yetna77alou définitivement.", "Cerbere ma yblockich e5er tir. Infecte wala Couple, ytir ki ymout sauf ken pénalité Ancien déjà na77at pouvoir mte3ou."),
        "red_riding_hoods": ("Pouvoirha passif: tant que fama Chasseur 7ay, attaque normale mta3 jme3et el loups ma to9telhech.", "Ki el Chasseurs lkol ymoutou, protection toufa. Sorciere, Loup Blanc, Chasseur, Barbier, vote w morts directes yo9tlouha normal.", "Ken Cerbere yblocki Chaperon Rouge, protection tetwa9ef ellila 7atta ken Chasseur 7ay. App twarri statut a7mer, w protection ترجع automatique ellila elli ba3dha."),
        "bears": ("Ba3d inscription bel QR code, narrateur yratteb el joueurs kif ma houma 9a3din bel s7i7. El lista mdawra: e5er joueur voisin mta3 louel.", "Kol lila el jeu ychouf a9reb zouz jiran 3aychin; Ours ygarger ken we7ed menhom loup wala infecté.", "Ba3d mawt, jiran yetbadlou. 9bal lil loula, narrateur ydecidi ken Ours infecte ygarger automatiquement, w ken resultat yet7seb doub yti7 el lil wala ba3d les pouvoirs.", "Cerbere y9aleb resultat: Ours ma ygargerch ken fama voisin loup, w ygarger ken jiranou moch loups."),
        "shepherds": ("Ba3d el distribution, narrateur ya5tar stock men 1 l 10 3lelech. Kol lil Berger ynajem ma yab3ath 7atta wa7ed wala yab3ath 9addech y7eb mel stock eli ba9a, kol wa7ed l joueur 3ayech mo5talef.", "3alouch yerja3 men cible moch loup; ma yerja3ch men loup wala joueur infecte. Ki youfaw, Berger ma3ach yfi9.", "Cerbere y9aleb kol resultat: 3alouch yerja3 mel loup w yedhi3 3and joueur moch loup. Berger infecte yab9a b role mte3ou."),
        "cupids": ("Awel lil yrabbet zouz joueurs mo5talfin w ynajem ya5tar rou7ou m3a joueur e5er.", "Infecte + loup normal yab9aw m3a jme3et el loups; infecte + Villageois wala role solo ywaliw Couple independent. Bla infection, ay Couple fih Alien ywali clan Alien.", "Cerbere yji ba3dou w ma ynajemch yfas5 lien. Pouvoirs individuels yab9aw w clan Couple yetbaddel ba3d infection wala transformation."),
        "judges": ("Kol lil y9aren zouz joueurs mo5talfin w ynajem ya5tar rou7ou m3a we7ed; ya3ref bark nafs clan wala mo5talfin.", "Yesta3mel clan actuel: Village w joueur infecte ya3tihom deux clans differents.", "Ken Cerbere blockeh, resultat yet9aleb: zouz Villageois yjiw clans mo5talfin, w Villageois m3a infecte, loup wala Alien yjiw nafs clan. Role yab9a."),
        "wild_children": ("Awel lil ya5tar joueur e5er idole mte3ou.", "Ki idole ymout, ayyan ken sabab — lil, vote, Barbier, Alien, Chasseur wala mawt en chaîne — Enfant Sauvage yod5ol physiquement m3a jme3et el loups.", "Transforme wala infecte, Ours, Berger w Juge y7esbouh loup, ama yab9a Enfant Sauvage w lien idole yab9a. Cerbere ma yfas5ch idole."),
        "angels": ("El game tebda dima b lil 1. Ba3d yal3ab solo 7atta awel vote w yerba7 ken houwa wa7dou yo5rej.", "Ken ma rba7ch, ywali Simple Villageois direct. Ken yab9a wa7dou 9bal vote, objectif yefchel w victoire normale tet7seb.", "Ken amoureux, objectif solo yetna77a direct; m3a Villageois yab9aw camp Village. Victoire Ange 9bal choix Servante."),
        "ankous": ("Ba3d ma ymout ma ya7kich, ama 3andou vote m5obi kol nhar pendant zouz votes; app tzidou automatiquement.", "Ken met fel lil ysawwet nafs nhar w elli ba3dou; ken met bel vote yabda fel zouz nharat elli ba3d. Passe yconsumi nhar.", "Cerbere ma yfas5ch votes. Ankou infecte yod5ol m3a jme3et el loups ama yab9a Ankou w ykamel zouz votes ba3d mawt, sauf ken pénalité Ancien na77at pouvoir mte3ou."),
        "little_girls": ("Tnajem t7ell 3iniha chwaya physiquement waqt tour loups bech ta3refhom, bla ecran w bla confirmation narrateur.", "Loups ya5tarou victime loula, ba3d ynajmou ybadlouha b ay joueur chefouh yetfarrej, que ce soit Petite Fille wala le. Ken cible finale wa7da tetdhareb.", "Cerbere yji ba3d. Petite Fille infectee tod5ol m3a jme3et el loups ama tab9a b role original. Protecteur, Pute, Sorciere w infection yesta3mlou cible finale."),
        "seers": ("Kol lil ta5tar joueur e5er w tchouf role eli interface twarrih.", "Loup Bleu ywarrilha role random. Ken cible infectee, tchouf ken role original w ma tchoufch infection. Ken Voyante bloquee tchouf Cerbere.", "Voyante infectee wala Couple tab9a Voyante w tkamel visions; clan bark yetbaddel."),
        "witches": ("Ba3d loups tchouf cible finale, w tnajem testa3mel zouz potions nafs ellila, kol wa7da marra bark.", "Vie tna77i mawt cible. Mort ma tnajemch ta5tar rou7ha; to9tel direct Alien, Pute wala Ancien, w Ancien yna77i pouvoirs Village.", "Ken Cerbere blockeha, tfi9 w ta5tar normal bla ma ta3ref: effets yetna77aw fel calcul w 7atta potion ma tetconsumach. Infectee wala Couple tab9a Sorciere."),
        "protectors": ("Kol lil ya7mi joueur men attaque jme3et el loups w ynajem ya7mi rou7ou, ama may7mich nafs cible zouz lilet metwalyin.", "Protection twa9ef zeda infection 3al cible, ama kartoucha Loup-Pere tetconsuma. Ma twa9efch Sorciere, Loup Blanc, Chasseur wala Barbier.", "Ken Cerbere blockih, protection ma te5demch ellila. Protecteur infecte yod5ol m3a jme3et el loups ama yab9a Protecteur w ykamel ya7mi."),
        "villagers": ("Ma 3andouch pouvoir fel lil; yra9eb, ya7ki, yethem w ysawwet m3a Village.", "Cerbere ma yna77ilou chay. Loup Noir ynajem yna77i klem w vote nhar, w Loup Bavard yefredh kelma.", "Infection tbaddel clan lel loups ama role Villageois yab9a. Fel Couple: infecte + loup normal yab9aw m3a jme3et el loups; infecte + Villageois wala role solo ywaliw Couple independent."),
    },
}
