"""Detailed, player-facing rules for the role guide page."""


ROLE_CAMPS = {
    "simple_wolves": "wolf", "infecting_fathers": "wolf", "cerberus_wolves": "wolf",
    "black_wolves": "wolf", "talkative_wolves": "wolf", "blue_wolves": "wolf",
    "white_wolves": "solo", "aliens": "solo", "angels": "solo",
    "barbers": "village", "prostitutes": "village", "servants": "village",
    "ancients": "village", "hunters": "village", "bears": "village",
    "shepherds": "village", "cupids": "village", "judges": "village",
    "wild_children": "variable", "ankous": "village", "little_girls": "village",
    "seers": "village", "witches": "village", "protectors": "village",
    "villagers": "village",
}


ROLE_CODES = {
    "simple_wolves": "LG", "infecting_fathers": "LPI", "cerberus_wolves": "LC",
    "black_wolves": "LN", "talkative_wolves": "LB", "blue_wolves": "BL",
    "white_wolves": "LW", "barbers": "BA", "aliens": "AL", "prostitutes": "PU",
    "servants": "SE", "ancients": "AN", "hunters": "CH", "bears": "OU",
    "shepherds": "BE", "cupids": "CU", "judges": "JU", "wild_children": "ES",
    "angels": "AG", "ankous": "AK", "little_girls": "PF", "seers": "VO",
    "witches": "SO", "protectors": "PR", "villagers": "VI",
}


ROLE_GUIDES = {
    "fr": {
        "simple_wolves": (
            "Se réveille avec la meute chaque nuit. La meute choisit une seule cible non-loup.",
            "Si les loups voient quelqu'un regarder, ils peuvent remplacer leur première cible par cette personne. Le narrateur ne confirme jamais son rôle.",
            "Le blocage du Loup Cerbère n'enlève aucune capacité spéciale au Loup simple. Infecté ou amoureux, son clan est recalculé selon les règles de l'infection et du Couple.",
        ),
        "infecting_fathers": (
            "Chasse avec la meute et possède une seule cartouche d'infection pour toute la partie. Il décide après le choix final des loups.",
            "Toute tentative consomme la cartouche, même si elle échoue. Protection, première vie de l'Ancien, Pute non bloquée, Alien et Servante font échouer l'infection.",
            "Le Cerbère bloque son tour d'infection sans consommer la cartouche. La cible conserve son rôle original et tous ses pouvoirs ; son Couple peut ensuite remplacer le clan loup selon les règles des amoureux.",
        ),
        "cerberus_wolves": (
            "Après l'attaque de la meute, choisit un autre joueur dont le pouvoir est bloqué pour la nuit en cours.",
            "Il annule notamment protection, redirection de la Pute, potions, infection, tir du Loup Blanc, silence, mot imposé, Ours et Berger. La Voyante bloquée ne voit que le Loup Cerbère ; le Juge bloqué reçoit toujours « Même clan ».",
            "Il ne retire pas les capacités passives absolues de l'Alien, de la Servante, de l'Ancien, du Chasseur, de l'Ankou ou de l'Ange. Il reste un loup normal pour les clans et les Couples.",
        ),
        "black_wolves": (
            "Se réveille seul chaque nuit et désigne le joueur réduit au silence le lendemain.",
            "Le joueur doit dire « Passe » pendant la parole et les accusations, et son vote ne compte pas.",
            "S'il est bloqué par le Cerbère, aucun silence n'est imposé. Il chasse toujours normalement avec la meute et suit les règles de clan du Couple.",
        ),
        "talkative_wolves": (
            "Se réveille seul, choisit un joueur et lui impose un mot à prononcer pendant sa prise de parole du lendemain.",
            "Le narrateur affiche le joueur et le mot pendant la journée. Le rôle ne tue personne directement.",
            "Le Cerbère annule le mot de cette nuit. Il reste membre physique de la meute pour l'Ours, le Berger, le Juge et les Couples.",
        ),
        "blue_wolves": (
            "Chasse normalement avec la meute, mais trompe la Voyante.",
            "Quand la Voyante le vise, l'interface affiche un rôle aléatoire parmi tous les rôles, y compris Loup Bleu.",
            "Bloquer le Loup Bleu ne retire pas son camouflage. Si la Voyante elle-même est bloquée, elle voit le Cerbère. Il appartient au clan loup sauf changement par Couple Alien ou mixte.",
        ),
        "white_wolves": (
            "Chasse avec la meute toutes les nuits. Les sous-rôles des loups restent cachés pendant leur discussion.",
            "Les nuits 2, 4, 6… il se réveille seul et peut tuer directement un autre membre physique de la meute, ou passer. Le Cerbère annule ce tir pour la nuit.",
            "Il est vu comme loup par le Juge, l'Ours et le Berger, mais gagne seul s'il reste le dernier survivant. Un Couple mixte ou Alien peut remplacer cet objectif de clan.",
        ),
        "barbers": (
            "La première nuit, convient d'un clin d'œil avec le narrateur. Pendant un jour, il peut utiliser une seule cartouche sur un joueur.",
            "Si la cible appartient physiquement aux loups, elle meurt seule. Sinon le Barbier et la cible meurent ensemble.",
            "Le Cerbère bloque son action pendant la journée concernée. Infecté ou en Couple, il conserve son rôle et son tir ; seul son clan de victoire est recalculé.",
        ),
        "aliens": (
            "Joue en solo. Après son signal, il peut attribuer un rôle à un ou plusieurs joueurs : une seule erreur le tue, les réponses correctes restent acquises.",
            "Il gagne s'il découvre tous les rôles requis ou s'il reste le dernier survivant. Les attaques de la meute et l'infection échouent toujours sur lui, mais la Sorcière peut le tuer.",
            "Le Cerbère bloque sa tentative de devinette, pas ses immunités. Un Couple contenant un Alien rejoint normalement le clan Alien ; si son partenaire est infecté, les deux forment exceptionnellement un Couple indépendant.",
        ),
        "prostitutes": (
            "Chaque nuit, choisit un autre joueur. Si la meute la cible, l'attaque est redirigée vers ce joueur.",
            "Elle résiste normalement à l'infection, mais la Sorcière peut la tuer directement. La cible redirigée peut encore être sauvée par sa propre protection.",
            "Si le Cerbère la bloque, redirection et immunité à l'infection disparaissent pour cette nuit : elle peut être infectée, rejoint alors la meute, mais reste Pute et récupère son pouvoir les nuits suivantes. En Couple, elle garde aussi son rôle.",
        ),
        "servants": (
            "Après une élimination par vote et avant l'annonce publique, peut prendre secrètement le rôle du joueur éliminé ou rester Servante.",
            "Si elle accepte, le village apprend que la Servante est morte et elle continue avec le nouveau rôle. Son lien amoureux reste attaché au joueur et le clan est recalculé.",
            "Elle ne peut jamais être infectée. Le Cerbère n'annule pas son choix après le vote. Prendre Ankou, Chasseur, Alien ou loup donne les règles complètes du nouveau rôle.",
        ),
        "ancients": (
            "Possède deux vies uniquement contre l'attaque normale de la meute. La première attaque enlève une vie, la seconde le tue.",
            "Potion de mort, tir du Chasseur, Barbier et autres morts directes le tuent immédiatement. S'il meurt par vote, tous les pouvoirs villageois vivants disparaissent sauf celui du Chasseur.",
            "La première tentative d'infection est absorbée comme une première attaque et consomme la cartouche ; une tentative après cette première vie peut réussir. Infecté, il rejoint la meute mais reste Ancien. Le Cerbère ne retire pas ses vies.",
        ),
        "hunters": (
            "Quand il meurt de nuit, par vote ou par le tir d'un autre Chasseur, il choisit un joueur vivant à emporter avec lui.",
            "Les tirs peuvent former une chaîne de Chasseurs. Il conserve son rôle même si l'Ancien meurt par vote.",
            "Le Cerbère n'annule pas son dernier tir. Infecté ou en Couple, il conserve son rôle et tire toujours à sa mort ; seul son clan est recalculé.",
        ),
        "bears": (
            "Chaque nuit, le narrateur vérifie ses deux voisins vivants les plus proches autour de la table. Il grogne si au moins un est loup ou infecté.",
            "Après une mort, les voisins sont recalculés : il peut continuer à grogner si le nouveau voisin est loup. Un Ours infecté garde son rôle mais ne grogne jamais à cause de lui-même.",
            "Le Cerbère empêche le grognement de cette nuit. L'infection le fait rejoindre la meute sans perdre son pouvoir ; le Juge et le Berger le considèrent alors comme loup.",
        ),
        "shepherds": (
            "Commence avec trois moutons. Chaque nuit, il peut en envoyer de un à trois vers des joueurs.",
            "Un mouton revient si la cible n'est pas membre physique de la meute ; il est perdu définitivement si la cible est loup. À zéro mouton, le Berger ne se réveille plus.",
            "Le Cerbère empêche tout envoi sans perdre de mouton. Infecté, il rejoint les loups mais reste Berger et continue ses envois. Son Couple change son clan, jamais son rôle ni le résultat des moutons.",
        ),
        "cupids": (
            "La première nuit, choisit deux joueurs différents et peut se choisir lui-même avec une autre personne.",
            "Deux membres du même camp continuent avec ce camp. Infecté + loup normal restent avec la meute ; infecté + villageois ou rôle solo forment un Couple indépendant. Sans infecté, tout Couple contenant un Alien rejoint le clan Alien.",
            "Le Cerbère agit après Cupidon et ne peut donc pas annuler le lien déjà créé. Les pouvoirs individuels restent actifs et le clan du Couple est recalculé après infection ou transformation.",
        ),
        "judges": (
            "Chaque nuit, compare deux joueurs différents et peut se choisir avec une autre personne. Il apprend seulement « même clan » ou « clans différents ».",
            "Le résultat utilise les clans actuels : Village, Loups, Alien ou Couple indépendant. Infection, Enfant Sauvage transformé, Ange expiré et Couples sont donc pris en compte.",
            "Le Cerbère fausse le verdict : le Juge choisit toujours deux joueurs, mais reçoit « Même clan » quelles que soient leurs véritables factions. Infecté, il reste Juge et continue ses comparaisons.",
        ),
        "wild_children": (
            "La première nuit, choisit un autre joueur comme modèle.",
            "Si ce modèle meurt pendant la nuit ou par le vote, l'Enfant Sauvage rejoint physiquement la meute tout en gardant son identité. Une autre cause de mort du modèle ne déclenche pas la transformation.",
            "Transformé ou infecté, il est détecté comme loup par Ours, Berger et Juge, mais conserve le rôle Enfant Sauvage et son lien d'idole. Le Cerbère n'annule pas le choix déjà fait.",
        ),
        "angels": (
            "Joue seul pendant le premier jour. S'il est l'unique éliminé par le vote final de ce jour, il gagne immédiatement seul.",
            "Si un autre joueur sort, si le vote est à égalité ou s'il est passé, sa chance expire et il rejoint définitivement le Village. Mourir la première nuit ne donne aucune victoire.",
            "Le Cerbère n'affecte pas cette condition. Infecté, il conserve le rôle Ange mais rejoint le clan loup et ne peut plus gagner avec l'objectif solo. Les règles du Couple peuvent aussi recalculer son clan.",
        ),
        "ankous": (
            "Après sa mort, ne parle plus mais conserve un vote par jour pendant exactement deux jours de vote.",
            "Mort de nuit : il vote le jour même puis le suivant. Mort par vote : ses deux votes commencent les deux jours suivants. Un jour où le vote est passé consomme quand même une journée.",
            "Le Cerbère n'annule pas ces votes posthumes. Infecté, il rejoint la meute mais reste Ankou et garde ses deux votes après sa mort. Seule une perte effective du rôle retire cet effet.",
        ),
        "little_girls": (
            "Peut entrouvrir les yeux physiquement pendant le tour des loups pour tenter de les reconnaître, sans écran ni confirmation du narrateur.",
            "Les loups choisissent d'abord une victime. S'ils voient quelqu'un regarder, ils peuvent choisir cette personne comme nouvelle cible, qu'elle soit réellement Petite Fille ou non. Une seule cible finale est attaquée.",
            "Le Cerbère agit après ce moment et ne confirme ni n'annule l'observation. Infectée, elle rejoint les loups mais conserve le rôle Petite Fille. Protection, Pute, Sorcière et infection utilisent la cible finale.",
        ),
        "seers": (
            "Chaque nuit, choisit un autre joueur et découvre le rôle affiché par l'interface.",
            "Le Loup Bleu renvoie un rôle entièrement aléatoire. Si la Voyante est bloquée par le Cerbère, elle ne voit que le Loup Cerbère, quelle que soit sa cible.",
            "Une infection la fait rejoindre les loups sans changer son rôle ni ses visions. La Voyante qui observe un infecté voit seulement son rôle original, jamais le statut infecté. En Couple elle garde aussi son pouvoir.",
        ),
        "witches": (
            "Après les loups, voit leur cible finale et possède une potion de vie et une potion de mort, utilisables une seule fois chacune.",
            "La vie annule la mort de la cible. La mort tue directement une autre personne et peut tuer Alien, Pute ou Ancien dès le premier coup.",
            "Le Cerbère fait sauter entièrement son tour sans consommer les potions. Infectée, elle rejoint les loups mais reste Sorcière et conserve ses potions restantes. Son Couple ne retire pas ses choix.",
        ),
        "protectors": (
            "Chaque nuit, choisit un joueur à protéger contre l'attaque de la meute. Il peut se choisir, mais jamais protéger la même personne deux nuits consécutives.",
            "La protection bloque aussi une tentative d'infection sur cette cible, mais la cartouche du Loup-Père est quand même consommée. Elle ne bloque pas potion de mort, Loup Blanc, Chasseur ou Barbier.",
            "Si le Cerbère bloque le Protecteur, son choix n'a aucun effet cette nuit et infection/attaque peuvent passer. Infecté, il rejoint les loups mais reste Protecteur et continue à protéger.",
        ),
        "villagers": (
            "N'a aucun pouvoir nocturne : il observe, discute, accuse et vote avec le Village.",
            "Le Cerbère ne lui retire rien. Le Loup Noir peut annuler sa parole et son vote pour un jour, et le Loup Bavard peut lui imposer un mot.",
            "Une infection le fait rejoindre les loups tout en gardant son rôle de Villageois. En Couple, il garde toujours son rôle original : infecté + loup restent avec la meute, tandis qu'infecté + villageois ou rôle solo deviennent un Couple indépendant.",
        ),
    },
    "en": {
        "simple_wolves": ("Wakes with the pack every night; the pack attacks one non-wolf target.", "If the Wolves see someone peeking, they may replace their first target with that person. The narrator never confirms the person's role.", "A Cerberus block removes no special power from a regular Wolf. Infection and Couple rules can still recalculate its faction."),
        "infecting_fathers": ("Hunts with the pack and owns one infection shot for the entire game, used after the pack's final choice.", "Every attempt spends the shot. Protection, the Elder's first life, an unblocked Escort, Alien and Servant make it fail.", "Cerberus skips the infection without spending the shot. The target keeps the original role and all powers; Couple rules may then override the Wolf winning faction."),
        "cerberus_wolves": ("After the pack attack, blocks one other player's power for the current night.", "It can cancel protection, Escort redirection, potions, infection, White Wolf shot, silence, required word, Bear and Shepherd. A blocked Seer sees Cerberus; a blocked Judge always receives “Same faction”.", "It does not remove absolute passive effects belonging to Alien, Servant, Elder, Hunter, Ankou or Angel. It is otherwise a physical Wolf."),
        "black_wolves": ("Wakes alone and silences one player for the following day.", "That player must answer “Pass” during discussion and accusations, and their vote is not counted.", "Cerberus cancels the silence for that night. The Black Wolf still hunts with the pack and follows Couple faction rules."),
        "talkative_wolves": ("Wakes alone, chooses a player and gives them a word they must say during the next day's speech.", "The narrator displays the player and required word during the day; this power does not kill directly.", "Cerberus cancels the word. The Talkative Wolf remains a physical pack member for Bear, Shepherd, Judge and Couples."),
        "blue_wolves": ("Hunts normally but deceives the Seer.", "When inspected, the interface displays a random role from every available role, including Blue Wolf.", "Blocking Blue Wolf does not remove the disguise; blocking the Seer shows Cerberus. Couple or Alien links may change its winning faction."),
        "white_wolves": ("Hunts with the pack every night while exact wolf sub-roles stay hidden from the pack.", "On nights 2, 4, 6… it wakes alone and may directly kill another physical pack member or pass. Cerberus cancels this shot.", "Bear, Shepherd and Judge treat it as a Wolf, but it normally wins alone as the last survivor. Mixed or Alien Couple rules may replace that objective."),
        "barbers": ("Agrees on a wink with the narrator on night one, then has one daytime shot against one player.", "A physical Wolf target dies alone. On a miss, both the Barber and the chosen target die.", "Cerberus blocks the daytime action. Infection or a Couple changes the faction, but the Barber keeps the original role and shot."),
        "aliens": ("Plays solo and may assign roles to one or more players after giving the signal. One error kills the Alien; correct answers remain saved.", "Wins after discovering all required roles or as the last survivor. Pack attacks and infection always fail, but the Witch can kill it.", "Cerberus blocks the guessing action, not immunity. A Couple containing Alien normally joins Alien; with an infected partner, it exceptionally becomes an independent Couple."),
        "prostitutes": ("Chooses another player nightly. If the pack targets the Escort, the attack is redirected to that player.", "Normally resists infection, while the Witch can kill directly. Protection is evaluated against the final redirected target.", "Cerberus removes redirection and infection immunity for that night. If infected, the Escort joins the pack but keeps the role and regains its power on later nights. A Couple never removes the role."),
        "servants": ("Before a voted player's role is announced, may secretly take that role or remain the Servant.", "On acceptance the village is told the Servant died, while the player continues with the new role. Lover status remains attached and the faction is recalculated.", "Can never be infected. Cerberus does not cancel the post-vote choice; taking Ankou, Hunter, Alien or Wolf grants the full new rules."),
        "ancients": ("Has two lives only against normal pack attacks: the first removes one life and the second kills.", "Witch, Hunter, Barber and other direct deaths kill immediately. A vote death removes every living Village power except Hunter.", "The first infection attempt consumes the shot and first life; a later attempt may work. An infected Elder joins the pack but remains the Elder. Cerberus never removes these lives."),
        "hunters": ("After dying at night, by vote or from another Hunter, chooses one living player to take along.", "Hunter shots can chain. Hunter keeps the role even when an Elder vote death removes other Village powers.", "Cerberus does not cancel the last shot. An infected or coupled Hunter keeps the original role and still shoots on death; only the faction changes."),
        "bears": ("The narrator checks the two closest living neighbours around the table; the Bear growls when at least one is a Wolf or infected.", "Neighbours are recalculated after deaths. An infected Bear keeps the role, joins the pack, and never growls because of itself.", "Cerberus prevents that night's growl. An infected Bear is treated as Wolf by Judge and Shepherd."),
        "shepherds": ("Starts with three sheep and may send one to three of them to players each night.", "A sheep returns from a non-pack target and is permanently lost against a physical Wolf or infected player. At zero sheep the Shepherd no longer wakes.", "Cerberus prevents all sending without losing sheep. An infected Shepherd joins the pack but keeps the role and sheep. A Couple changes faction, never the original role."),
        "cupids": ("On night one, links two different players and may include Cupid in the pair.", "Same-faction lovers stay together. Infected + normal Wolf remain with the pack; infected + Villager or solo role form an independent Couple. Without infection, any pair containing Alien joins Alien.", "Cerberus acts later and cannot cancel the link. Individual powers remain and the Couple faction is recalculated after infection or transformation."),
        "judges": ("Compares two different players nightly and may choose self plus another player; only learns same or different faction.", "Uses current Village, Wolf, Alien or independent Couple factions: a Village player and an infected player are in different factions.", "Cerberus falsifies the verdict: the Judge still chooses two players but always receives “Same faction”. An infected or coupled Judge keeps the role."),
        "wild_children": ("Chooses another player as a role model on the first night.", "Joins the physical pack if the model dies at night or by vote. Other causes of the model's death do not trigger the change.", "After changing or infection, Bear, Shepherd and Judge detect a Wolf, but the original Wild Child role and saved model remain. Cerberus does not cancel the model."),
        "angels": ("Plays solo on day one and wins alone if uniquely eliminated by that day's final vote.", "If someone else leaves, the vote ties, or voting is skipped, the chance expires and Angel permanently joins Village. A night-one death is not a win.", "Cerberus does not affect the condition. An infected Angel keeps the role but joins the Wolf faction and loses the solo win; Couple rules can also recalculate the faction."),
        "ankous": ("After death, cannot speak but keeps one vote per day for exactly two voting days.", "A night death allows votes that day and the next; a vote death starts on the following two days. A skipped vote still consumes a day.", "Cerberus does not cancel ghost votes. An infected Ankou joins the pack but remains Ankou and keeps both post-death votes. Only an actual role loss removes the effect."),
        "little_girls": ("May physically peek during the Wolves' turn to identify them, without screen help or narrator confirmation.", "Wolves first choose a victim, then may replace it with anyone they saw peeking, whether that person is really Little Girl or not. Only the final target is attacked.", "Cerberus acts later and neither confirms nor cancels peeking. An infected Little Girl joins the pack but keeps the original role; protection, Escort, Witch and infection use the final target."),
        "seers": ("Inspects another player every night and sees the role displayed by the interface.", "Blue Wolf produces a completely random role. For an infected target, the Seer sees only the original role and never the infection. A blocked Seer sees Cerberus.", "An infected or coupled Seer keeps the original role and all future visions; only the winning faction is recalculated."),
        "witches": ("Acts after the Wolves, sees their final target, and owns one life potion plus one death potion.", "Life cancels the target's death. Death directly kills another player and can kill Alien, Escort or Elder on the first hit.", "Cerberus skips the whole turn without spending potions. An infected or coupled Witch keeps the role and remaining potions; only the faction changes."),
        "protectors": ("Protects one player from the pack each night and may protect self, but never the same target on two consecutive nights.", "Also stops infection on that target, although the Alpha's shot is still consumed. It does not stop Witch, White Wolf, Hunter or Barber deaths.", "Cerberus makes that night's protection ineffective. An infected Protector joins the pack but keeps the role and continues protecting."),
        "villagers": ("Has no night power; watches, discusses, accuses and votes with Village.", "Cerberus removes nothing. Black Wolf can remove speech and vote for a day, while Talkative Wolf can impose a word.", "Infection changes the faction to Wolf but preserves the original Villager role. In a Couple, infected + normal Wolf stay with the pack, while infected + Villager or solo role form an independent Couple."),
    },
    "tn": {
        "simple_wolves": ("Yfi9 m3a el meute kol lil w ya5tarou cible wa7da moch loup.", "Ken chefou joueur yetfarrej, ynajmou ybadlou cible loula bih. El narrateur ma yconfirmi 7atta role.", "Blocage Cerbere ma yna77ilou 7atta pouvoir special. Infection w Couple ynajmou ybadlou clan mte3ou."),
        "infecting_fathers": ("Ysayyed m3a el meute w 3andou kartoucha infection wa7da fel game, ba3d choix final mta3 loups.", "Ay tentative tconsumi kartoucha. Protection, awel vie mta3 Ancien, Pute moch bloquee, Alien w Servante yfachelou infection.", "Cerbere yblocki tour infection ama kartoucha tab9a. Cible teb9a b role original w pouvoirs lkol; regles Couple ynajmou ba3d ybaddlou clan loup."),
        "cerberus_wolves": ("Ba3d attaque mta3 meute, yblocki pouvoir mta3 joueur e5er lel lila hedhi.", "Ynajem yna77i protection, renvoi Pute, potions, infection, tir Loup Blanc, silence, kelma, Ours w Berger. Voyante bloquee tchouf Cerbere; Juge bloque yjiwh dima Nafs el clan.", "Ma yna77ich immunites absolues mta3 Alien, Servante, Ancien, Chasseur, Ankou wala Ange. Houwa loup physique normal."),
        "black_wolves": ("Yfi9 wa7dou w ysakket joueur lel nhar elli ba3dou.", "Joueur y9oul ken Passe fel parole w accusations, w vote mte3ou ma yet7sebch.", "Cerbere yfas5 silence mta3 ellila. Loup Noir ykammel ysayyed m3a meute w yetba3 regles Couple."),
        "talkative_wolves": ("Yfi9 wa7dou, ya5tar joueur w ya3tih kelma lezem y9oulha 8odwa fi klemou.", "El narrateur ywarrri joueur w kelma fel nhar; pouvoir hedha ma yo9telch direct.", "Cerbere yfas5 kelma. Houwa membre physique mel meute lel Ours, Berger, Juge w Couples."),
        "blue_wolves": ("Ysayyed normal m3a meute ama y8alet el Voyante.", "Ki Voyante ta5tarou, interface twarri role random men les roles lkol, inclus Loup Bleu.", "Blocage mta3 Loup Bleu ma yna77ich camouflage; ken Voyante bloquee tchouf Cerbere. Couple wala Alien ynajem ybaddel clan victoire."),
        "white_wolves": ("Ysayyed m3a meute kol lil w sous-roles mta3 loups yab9aw me5byin fel discussion.", "Fel lil 2, 4, 6… yfi9 wa7dou, ynajem yo9tel membre physique mel meute wala passe. Cerbere yblocki tir hedha.", "Ours, Berger w Juge y7esbouh loup, ama normalement yerba7 wa7dou ken yab9a e5er 3ayech. Couple mixte wala Alien ynajem ybaddel objectif."),
        "barbers": ("Awel lil yetfehem 3la 8amza m3a narrateur, w 3andou kartoucha wa7da fel nhar 3la joueur.", "Ken cible loup physique tmout wa7adha. Ken guess 8alet, Barbier w cible ymoutou zouz.", "Cerbere yblocki action fel nhar. Infection wala Couple tbaddel clan bark; role Barbier w kartoucha yab9aw."),
        "aliens": ("Yal3ab solo. Ba3d signal, yguessi role mta3 joueur wa7ed wala barcha; 8alta wa7da tmoutou w s7a7 yet7afdhoulou.", "Yerba7 ki yekchef roles elli lezem wala ki yab9a e5er 3ayech. Attaque loups w infection dima ma ynej7ouch, ama Sorciere tnajem to9tlou.", "Cerbere yblocki guess moch immunite. Couple fih Alien normalement ywali clan Alien; ken partenaire infecte, ywaliw Couple independent."),
        "prostitutes": ("Kol lil ta5tar joueur e5er. Ken meute ta5tarha, attaque temchi lel joueur hedheka.", "Normalement infection ma temchich fiha, ama Sorciere tnajem to9telha. Protection tet7seb 3la cible finale.", "Ken Cerbere blockeha, tnajem tetinfecta. Tod5ol lel meute ama tab9a Pute w pouvoir yarja3 lelet o5ra. Couple zeda ma yna77ich role."),
        "servants": ("9bal annonce mta3 joueur eli 5raj bel vote, tnajem te5ou role mte3ou bel sir wala tab9a Servante.", "Ken te5ouh, village yesma3 elli Servante metet w hiya tkammel b role jdid. Lien Couple yab9a w clan yet3awed yet7seb.", "Matetinfectech jemla. Cerbere ma yfas5ch choix ba3d vote; ken te5ou Ankou, Chasseur, Alien wala loup te5ou regles kemla."),
        "ancients": ("3andou zouz vies ken contre attaque normale mta3 meute: loula tna77i vie w thenya to9tlou.", "Sorciere, Chasseur, Barbier w mawt direct yo9tlouh men awel marra. Ken ymout bel vote, pouvoirs Village lkol yetna77aw sauf Chasseur.", "Awel tentative infection tconsumi kartoucha w awel vie; ba3dha tnajem tenja7. Ancien infecte yod5ol meute ama yab9a Ancien. Cerbere ma yna77ich vies."),
        "hunters": ("Ki ymout fel lil, bel vote wala b tir Chasseur e5er, ya5tar joueur 3ayech yhezou m3ah.", "Tirs ynajmou ya3mlou chaine. Chasseur yeb9a b role mte3ou 7atta ken Ancien ymout bel vote.", "Cerbere ma yblockich e5er tir. Infecte wala Couple, yab9a Chasseur w dima ytir ki ymout; clan bark yetbaddel."),
        "bears": ("Narrateur ychouf a9reb zouz jiran 3aychin; Ours ygarger ken we7ed menhom loup wala infecté.", "Ba3d mawt, jiran yetbadlou. Ours infecte yeb9a Ours, yod5ol meute w ma ygargerch 3la rou7ou.", "Cerbere ywa9ef gargar ellila. Ours infecte yet7seb loup 3and Juge w Berger."),
        "shepherds": ("Yabda b 3 3lelech w ynajem yab3ath men 1 l 3 kol lil.", "3alouch yerja3 men cible moch loup; ma yerja3ch men loup wala joueur infecte. Ki youfaw, Berger ma3ach yfi9.", "Cerbere ywa9ef envoi bla perte. Berger infecte yod5ol meute ama yab9a Berger b 3lelechou. Couple ybaddel clan bark, moch role."),
        "cupids": ("Awel lil yrabbet zouz joueurs mo5talfin w ynajem ya5tar rou7ou m3a joueur e5er.", "Infecte + loup normal yab9aw m3a meute; infecte + Villageois wala role solo ywaliw Couple independent. Bla infection, ay Couple fih Alien ywali clan Alien.", "Cerbere yji ba3dou w ma ynajemch yfas5 lien. Pouvoirs individuels yab9aw w clan Couple yetbaddel ba3d infection wala transformation."),
        "judges": ("Kol lil y9aren zouz joueurs mo5talfin w ynajem ya5tar rou7ou m3a we7ed; ya3ref bark nafs clan wala mo5talfin.", "Yesta3mel clan actuel: Village w joueur infecte ya3tihom deux clans differents.", "Ken Cerbere blockeh, Juge ya5tar zouz normal ama resultat dima Nafs el clan, 7atta ken Villageois m3a infecte, loup wala Alien. Role yab9a."),
        "wild_children": ("Awel lil ya5tar joueur e5er idole mte3ou.", "Ken idole ymout fel lil wala bel vote, Enfant Sauvage yod5ol physiquement lel meute. Cause mawt o5ra ma t7awwlouch.", "Transforme wala infecte, Ours, Berger w Juge y7esbouh loup, ama yab9a Enfant Sauvage w lien idole yab9a. Cerbere ma yfas5ch idole."),
        "angels": ("Yal3ab solo nhar louel w yerba7 wa7dou ken houwa wa7dou yo5rej bel vote final.", "Ken joueur e5er yo5rej, vote egalite wala passe, chance toufa w Ange ywali m3a Village. Ken ymout awel lil ma yerba7ch.", "Ange infecte yab9a b role Ange ama yal3ab m3a loups w ma3ach yerba7 solo. Couple zeda ynajem ybaddel clan."),
        "ankous": ("Ba3d ma ymout ma ya7kich, ama yo93od ysawwet marra kol nhar pendant zouz nharat vote.", "Ken met fel lil ysawwet nafs nhar w elli ba3dou; ken met bel vote yabda fel zouz nharat elli ba3d. Passe yconsumi nhar.", "Cerbere ma yfas5ch votes. Ankou infecte yod5ol meute ama yab9a Ankou w ykamel zouz votes ba3d mawt. Ken role nafssou yetna77a bark effet ydhi3."),
        "little_girls": ("Tnajem t7ell 3iniha chwaya physiquement waqt tour loups bech ta3refhom, bla ecran w bla confirmation narrateur.", "Loups ya5tarou victime loula, ba3d ynajmou ybadlouha b ay joueur chefouh yetfarrej, que ce soit Petite Fille wala le. Ken cible finale wa7da tetdhareb.", "Cerbere yji ba3d. Petite Fille infectee tod5ol meute ama tab9a b role original. Protecteur, Pute, Sorciere w infection yesta3mlou cible finale."),
        "seers": ("Kol lil ta5tar joueur e5er w tchouf role eli interface twarrih.", "Loup Bleu ywarrilha role random. Ken cible infectee, tchouf ken role original w ma tchoufch infection. Ken Voyante bloquee tchouf Cerbere.", "Voyante infectee wala Couple tab9a Voyante w tkamel visions; clan bark yetbaddel."),
        "witches": ("Ba3d loups tchouf cible finale, w 3andha potion vie w potion mort, kol wa7da marra bark.", "Vie tna77i mawt cible. Mort to9tel direct joueur e5er w tnajem to9tel Alien, Pute wala Ancien men awel dharba.", "Cerbere yfawwet tour bla consommation. Sorciere infectee wala Couple tab9a Sorciere w t7afe4 3la potions; clan bark yetbaddel."),
        "protectors": ("Kol lil ya7mi joueur men attaque meute w ynajem ya7mi rou7ou, ama may7mich nafs cible zouz lilet metwalyin.", "Protection twa9ef zeda infection 3al cible, ama kartoucha Loup-Pere tetconsuma. Ma twa9efch Sorciere, Loup Blanc, Chasseur wala Barbier.", "Ken Cerbere blockih, protection ma te5demch ellila. Protecteur infecte yod5ol meute ama yab9a Protecteur w ykamel ya7mi."),
        "villagers": ("Ma 3andouch pouvoir fel lil; yra9eb, ya7ki, yethem w ysawwet m3a Village.", "Cerbere ma yna77ilou chay. Loup Noir ynajem yna77i klem w vote nhar, w Loup Bavard yefredh kelma.", "Infection tbaddel clan lel loups ama role Villageois yab9a. Fel Couple: infecte + loup normal yab9aw meute; infecte + Villageois wala role solo ywaliw Couple independent."),
    },
}
